language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/chad-autry/relative-file-inliner
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
deploy:
   provider: npm
   email: "chad.autry@gmail.com"
   api_key: "$NPM_TOKEN"
   on:
     tags: true